SET (CMAKE_C_COMPILER mpicc CACHE FILEPATH "Dummy comment" FORCE)
SET (CMAKE_C_FLAGS "  -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -fvisibility=hidden -g3 " CACHE STRING "Dummy comment" FORCE)
SET (PETSC_CUDA_HOST_FLAGS ,-Wall,-Wwrite-strings,-Wno-strict-aliasing,-Wno-unknown-pragmas,-fvisibility=hidden,-g3 CACHE STRING "Dummy comment" FORCE)
SET (CMAKE_Fortran_COMPILER mpifort CACHE FILEPATH "Dummy comment" FORCE)
SET (CMAKE_Fortran_FLAGS " -Wall -ffree-line-length-0 -Wno-unused-dummy-argument -g  " CACHE STRING "Dummy comment" FORCE)
SET (CMAKE_AR /usr/bin/ar CACHE FILEPATH "Dummy comment" FORCE)
SET (CMAKE_RANLIB /usr/bin/ranlib CACHE FILEPATH "Dummy comment" FORCE)
