AC_INIT(Yambo, 5.1.0 r.20180 h.b35f39ffe, yambo@yambo-code.org)
SVERSION="5"
SSUBVERSION="1"
SPATCHLEVEL="0"
SREVISION="20180"
SHASH="b35f39ffe"
AC_SUBST(SVERSION)
AC_SUBST(SSUBVERSION)
AC_SUBST(SPATCHLEVEL)
AC_SUBST(SREVISION)
AC_SUBST(SHASH)
