
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = nleigsf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepc
LOCDIR   = src/nep/impls/nleigs/ftn-auto/
include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
