
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = adaptbasicf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscts
LOCDIR   = src/ts/adapt/impls/basic/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
