AC_INIT(Yambo, 4.2.0 r.14559 h.7fcce7e, yambo@yambo-code.org)
SVERSION="4"
SSUBVERSION="2"
SPATCHLEVEL="0"
SREVISION="14559"
SHASH="7fcce7e"
AC_SUBST(SVERSION)
AC_SUBST(SSUBVERSION)
AC_SUBST(SPATCHLEVEL)
AC_SUBST(SREVISION)
AC_SUBST(SHASH)
