
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dtextf.c drectf.c dsavef.c dtrif.c dclearf.c dellipsef.c dviewpf.c dpausef.c dmousef.c dlinef.c drawf.c dcoorf.c dmarkerf.c drawregf.c dflushf.c dpointf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscsys
LOCDIR   = src/sys/classes/draw/interface/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
